version: "3"
services:
  wallet-service-rest:
    image: wallet-service-rest
    restart: unless-stopped
    build: ./wallet-service-rest
    environment:
      PORT: 8080
    ports:
      - "8081:8080"
  wallet-service-grpc:
    image: wallet-service-grpc
    restart: unless-stopped
    build: ./wallet-service-grpc
    environment:
      PORT: 9090
    ports:
      - "9090:9090"
  account-service:
    image: account-service
    restart: unless-stopped
    build: ./account-service
    environment:
      PORT: 8080
      WALLET_SERVICE_GRPC_HOST: wallet-service-grpc
      WALLET_SERVICE_GRPC_PORT: 9090
      WALLET_SERVICE_REST_URL: http://wallet-service-rest:8080
    ports:
      - "8080:8080"
