version: "3"
services:
  wallet-service-rest:
    image: wallet-service-rest
    restart: unless-stopped
    build: ./wallet-service-rest
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
  wallet-service-grpc:
    image: wallet-service-grpc
    restart: unless-stopped
    build: ./wallet-service-grpc
    environment:
      PORT: 9090
    ports:
      - "9090:9090"
